---
test_name: hyperconverged_jenkins_upgrade_on_k8s

jenkins_link: https://raw.githubusercontent.com/openebs/openebs/master/k8s/demo/jenkins/jenkins.yml

pod_yaml_alias: jenkins.yml

ver_lts: lts

ver_2_124: 2.124

ver_2_125: 2.125

namespace: jenkins-upgrade

job_config_files: 
  - template.xml
  - config_change.sh

test_pod_regex: maya*|openebs*|node*|jenkins*|target*|cstor*

test_log_path: setup/logs/jenkins_test.log
