---

- name: Get the pvc name.
  shell: source ~/.profile; kubectl get pvc -n {{ namespace }} | grep jenkins-claim | awk {'print $3'}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: pv
  changed_when: true

- include_tasks: "{{utils_path}}/delete_deploy.yml"
  vars:
    ns: "{{ namespace }}"
    app_yml: "{{ pod_yaml_alias }}"

- include_tasks: "{{utils_path}}/delete_deploy_check.yml"
  vars:
    ns: "{{ namespace }}"
    lkey: app
    lvalue: jenkins-app

- name: Confirm pvc pod has been deleted
  shell: source ~/.profile; kubectl get pods -n {{ namespace }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: "pv.stdout not in result.stdout"
  delay: 30
  retries: 10
  changed_when: true

- name: Remove test artifacts
  file:
    path: "{{ result_kube_home.stdout }}/{{ item }}"
    state: absent
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  with_items:
         - "{{job_config_files}}"
         - "{{pod_yaml_alias}}"
