---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jiva-1r-raa
  annotations:
    cas.openebs.io/create-volume-template: jiva-volume-create-default-0.7.0
    cas.openebs.io/delete-volume-template: jiva-volume-delete-default-0.7.0
    cas.openebs.io/read-volume-template: jiva-volume-read-default-0.7.0
    cas.openebs.io/config: |
      - name: ControllerImage
        value: openebs/jiva:0.6.0
      - name: ReplicaImage
        value: openebs/jiva:0.6.0
      - name: VolumeMonitorImage
        value: openebs/m-exporter:ci
      - name: ReplicaCount
        value: "1"
      - name: StoragePool
        value: default
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "1"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jiva-vol1-1r-raa-claim
  labels:
    openebs.io/replica-anti-affinity: application-name
spec:
  storageClassName: jiva-1r-raa
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4G
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jiva-vol2-1r-raa-claim
  labels:
    openebs.io/replica-anti-affinity: application-name
spec:
  storageClassName: jiva-1r-raa
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4G
