---
apiVersion: v1
kind: Pod
metadata:
  name: test-vdbench
  labels:
    name: test-vdbench
spec:
  containers:
  - resources:
      limits:
        cpu: 0.5
    name: test-vdbench
    image: openebs/tests-vdbench
    volumeMounts:
    - mountPath: /datadir1
      name: demo-vsm1-vol1
  volumes:
  - name: demo-vsm1-vol1
    flexVolume:
      driver: "openebs/openebs-iscsi"
      fsType: "ext4"
      options:
        name: "demo-vsm1-vol1"
        source: "/tmp/openebs-iscsi"
        mountOptions: "dir_mode=0755,file_mode=0644,rw"
        openebsApiUrl: "http://172.28.128.5:5656/latest/"
        size: "10Gi"
        debug: "1"
