---
apiVersion: v1
kind: Pod
metadata:
  name: test-vdbench
  labels:
    name: test-vdbench
spec:
  containers:
  - resources:
      limits:
        cpu: 0.5
    name: test-vdbench
    image: openebs/tests-vdbench
    volumeMounts:
    - mountPath: /datadir1
      name: demo-vsm1-vol1
  volumes:
  - name: demo-vsm1-vol1
    iscsi:
      targetPortal: 172.28.128.101:3260      
      iqn: iqn.2016-09.com.openebs.jiva:demo-vsm1-vol1
      lun: 1
      fsType: ext4
      readOnly: false
