---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
  - resources:
      limits:
        cpu: 0.5
    name: mysql
    image: mysql
    args:
      - "--ignore-db-dir"
      - "lost+found"
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: k8sDem0
    ports:
      - containerPort: 3306
        name: mysql
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: demo-vsm1-vol1
  volumes:
  - name: demo-vsm1-vol1
    iscsi:
      targetPortal: 172.28.128.101:3260      
      iqn: iqn.2016-09.com.openebs.jiva:demo-vsm1-vol1
      lun: 1
      fsType: ext4
      readOnly: false
