---
apiVersion: v1
kind: Pod
metadata:
  name: tests-vdbench
  labels:
    name: tests-vdbench
spec:
  containers:
  - resources:
      limits:
        cpu: 0.5
    name: tests-vdbench
    image: openebs/tests-vdbench
    volumeMounts:
    - mountPath: /datadir1
      name: demo-vsm1-vol1
  volumes:
  - name: demo-vsm1-vol1
    flexVolume:
      driver: "openebs/openebs-iscsi"
      options:
        name: "demo-vsm1-vol1"
        openebsApiUrl: "http://172.28.128.5:5656/latest"
        size: "5G"
        debug: "1"
