apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-cstor-r1
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "sparse-claim-auto"
      - name: ReplicaCount
        value: "1"
      #To pin the target to the node where pool is provisioned, 
      #provide the hostname label as follows.
      #- name: TargetNodeSelector
      #  value: |-
      #      "kubernetes.io/hostname": "gke-kmova-helm-default-pool-a169cf59-kxfm"
provisioner: openebs.io/provisioner-iscsi
---
