---
- name: Wait some time
  wait_for:
    timeout: 50

- name: Delete Percona deployment
  shell: kubectl delete -f "{{ percona_link }}" -n "{{namespace}}"
  args:
    executable: /bin/bash
  register: del_out
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  until: "'percona' and 'deleted' in del_out.stdout"
  delay: 90
  retries: 5
  changed_when: true

- name: Remove copied files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ patch_file }}"
    - "{{ create_sc }}"
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

- name: Delete the namespace
  shell: kubectl delete ns "{{ namespace }}"
  args:
    executable: /bin/bash
  register: ns_delete
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  until: "'deleted' in ns_delete.stdout"
  delay: 30
  retries: 5
  changed_when: true

- name: Check whether the namespace is deleted
  shell: kubectl get ns
  args:
    executable: /bin/bash
  register: ns_out
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  until: '"{{ namespace }}" not in ns_out.stdout'
  delay: 60
  retries: 15
  changed_when: true
