---
test_name: verify_replica_deployment_with_node_affinity

patch_file: replica_patch.yaml

create_sc: storage-class.yaml

percona_link: https://raw.githubusercontent.com/openebs/openebs/master/k8s/demo/percona/demo-percona-mysql-pvc.yaml

replica_count: 2 
