---
- name: Wait some time
  wait_for:
    timeout: 50

- name: Delete Percona deployment
  shell: kubectl delete -f "{{ percona_link }}"
  args:
    executable: /bin/bash
  register: del_out
  until: "'percona' and 'deleted' in del_out.stdout"
  delay: 30
  retries: 5

- name: Remove copied files
  shell: rm -rf "{{ patch_file }}" "{{ create_sc }}"
  args:
    executable: /bin/bash

- name: Getting OpenEBS chart name
  shell: helm ls --all | grep openebs | grep DEPLOYED | awk '{print $1}'
  args:
    executable: /bin/bash
  register: charts

- name: Uninstall OpenEBS
  shell: helm del --purge "{{charts.stdout}}"
  args:
    executable: /bin/bash
  register: purge_out
  until: "'deleted' in purge_out.stdout"
  delay: 20
  retries: 10

- name: Check if OpenEBS namespace is deleted.
  shell: kubectl get ns
  args:
    executable: /bin/bash
  register: ns_out
  until: "'openebs' not in ns_out.stdout"
  delay: 20
  retries: 6

