---

- name: Wait some time
  wait_for:
    timeout: 50

- name: Delete Percona deployment
  shell: source ~/.profile; kubectl delete -f "{{ percona }}" -n "{{namespace}}"
  args:
    executable: /bin/bash
  register: del_out
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  until: "'percona' and 'deleted' in del_out.stdout"
  delay: 90
  retries: 5

- name: Delete storage class
  shell: source ~/.profile; kubectl delete -f "{{ result_kube_home.stdout }}/{{ create_sc }}"
  args:
    executable: /bin/bash
  register: sc_out
  until: "'deleted' in sc_out.stdout"
  delay: 10
  retries: 5
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  changed_when: True

- name: Remove copied files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ result_kube_home.stdout }}/{{ patch_file }}"
    - "{{ result_kube_home.stdout }}/{{ create_sc }}"
    - "{{ result_kube_home.stdout }}/{{ percona }}"
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

