
- name: Get pv name to verify successful deletion
  shell: source ~/.profile; kubectl get pvc -n {{ namespace }} | grep {{ volume_claim }} | awk {'print $3'}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: pv
  changed_when: True

- include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/delete_deploy.yml"
  vars:
    ns: "{{ namespace }}"
    app_yml: "{{ openebs_pvc }}"

- name: Confirm PVC pod has been deleted
  shell: source ~/.profile; kubectl get pods -n {{namespace}}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: "pv.stdout not in result.stdout"
  delay: 30
  retries: 10
  changed_when: True

- name: Delete Storage_pool path
  shell: source ~/.profile; kubectl delete -f "{{ storage_pool_path_creation }}"
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  changed_when: True

- name: Remove test artifacts
  file:
    path: "{{ result_kube_home.stdout }}/{{ item }}"
    state: absent
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  with_items:
      - "{{test_artifacts}}"



