---
- name: Get pv name to verify successful pvc deletion
  shell: source ~/.profile; kubectl get pvc {{ replace_with.0 }} -n {{ namespace }} -o custom-columns=:spec.volumeName --no-headers
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: pv
  changed_when: true

- name: Wait {{ mysql_load_duration }} sec for I/O completion
  wait_for:
    timeout: "{{ mysql_load_duration }}"

- name: Delete percona mysql pod
  include_tasks: "{{utils_path}}/delete_deploy.yml"
  vars:
    ns: "{{ namespace }}"
    app_yml: "{{ pod_yaml_alias }}"

- include_tasks: "{{utils_path}}/delete_deploy_check.yml"
  vars:
    ns: "{{ namespace }}"
    lkey: name
    lvalue: percona

- name: Remove test artifacts
  file:
    path: "{{ result_kube_home.stdout }}/{{ pod_yaml_alias }}"
    state: absent
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

- name: Confirm pvc pod has been deleted
  shell: source ~/.profile; kubectl get pods
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: "pv.stdout not in result.stdout"
  delay: 30
  retries: 10
  changed_when: true


