###########################################################################################
# PLAYBOOK NAME: iometer-demo
# PLAYBOOK DETAILS: Sets up env for IOmeter run on the storage by running dynamo from container
# PLAYBOOK NOTES:
#    a) Keep IOmeter application started on a windows machine before running playbook
#    b) Windows IOmeter host IP address can be set in ./roles/iometer/defaults/main.yml
#    c) Volume properties can be set in ./roles/volume/defaults/main.yml
#
- include: playbooks/test-iometer/iometer-prerequisites.yml
- include: playbooks/test-iometer/iometer.yml 
#
###########################################################################################
