---
- hosts: openebs-mayamasters
  roles:
    - {role: master, when: deployment_mode == "dedicated"}
    - {role: vagrant, when: is_vagrant_vm | bool and deployment_mode == "dedicated"}

- hosts: openebs-mayahosts
  roles:
    - {role: hosts, when: deployment_mode == "dedicated"}
    - {role: vagrant, when: is_vagrant_vm | bool and deployment_mode == "dedicated"}

- hosts: kubernetes-kubemasters 
  roles: 
<<<<<<< HEAD
    - {role: k8s-openebs-operator-helm, when: deployment_mode == "hyperconverged" and openebs_deploy == "helm"}

- hosts: kubernetes-kubemasters
  roles:
    - {role: k8s-openebs-operator, when: deployment_mode == "hyperconverged" and openebs_deploy == "kubectl"}
=======
    - {role: k8s-openebs-operator-helm, when: deployment_mode == "hyperconverged"}
>>>>>>> 24902556589f6822d183fc625e15f51e020f5618

