---
- name: Get $HOME of K8s master for kubernetes user
  shell: source ~/.profile; echo $HOME
  args:
    executable: /bin/bash
  register: result_kube_home
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  changed_when: true

- template:
    src: default-jiva.j2
    dest: "{{ result_kube_home.stdout }}"

- template:
    src: default-cstor.j2
    dest: "{{ result_kube_home.stdout }}"

- block:
     
    - name: Create storage class
      shell: source ~/.profile; kubectl apply -f {{result_kube_home.stdout}}/default-jiva.j2
      args:
        executable: /bin/bash
      register: sc
      until: "'created' in sc.stdout"
      delay: 15
      retries: 5

  when: storage_engine == 'jiva'

- block:

    - name: Create storage class
      shell: source ~/.profile; kubectl apply -f {{result_kube_home.stdout}}/default-cstor.j2
      args:
        executable: /bin/bash
      register: sc
      until: "'created' in sc.stdout"
      delay: 15
      retries: 5
  when: storage_engine == 'cStor'

- name: Remove the copied templates
  file:
    path: "{{result_kube_home.stdout}}/{{item}}"
    state: absent
  with_items:
    - default-jiva.j2
    - default-cstor.j2

