---
- name: Delete the openebs operator 
  shell: source ~/.profile; kubectl delete -f {{ openebs_operator_alias }}
  args: 
    executable: /bin/bash

- name: Confirm pod has been deleted
  shell: source ~/.profile; kubectl get pods 
  args:
    executable: /bin/bash
  register: result
  until: "'maya-apiserver' not in result.stdout"
  delay: 10
  retries: 3


  

