---
- name: Update Nomad IP in .profile  
  lineinfile:
    destfile : "{{ansible_env.HOME}}/.profile"
    line: export NOMAD_ADDR=http://{{hostvars[groups['openebs-mayamasters'][0]]['ansible_ssh_host']}}:4646
    state: present

- name: Update M-APIServer IP in .profile
  lineinfile:
    destfile : "{{ansible_env.HOME}}/.profile"
    line: export MAPI_ADDR=http://{{hostvars[groups['openebs-mayamasters'][0]]['ansible_ssh_host']}}:5656
    state: present
