---
apiVersion: v1
kind: ConfigMap
metadata:
  name: basic
data:

 basic-rw: |-

     [global]
     thread=32
     bs=64k
     direct=1
     ioengine=sync

     [write-phase]
     directory=/datadir
     rw=write
     do_verify=0

---
apiVersion: batch/v1
kind: Job
metadata:
  name: fio
spec:
  template:
    metadata:
      name: fio
    spec:
      restartPolicy: Never
      containers:
      - name: perfrunner
        image: openebs/tests-fio
        command: ["/bin/bash"]
        args: ["-c", "./fio_runner.sh --size 5g --duration 60; exit 0"]
        volumeMounts:
           - mountPath: /datadir
             name: demo-vol1
           - mountPath: templates/file/basic-rw
             subPath: basic-rw
             name: basic-configmap
        tty: true

      volumes:
      - name: demo-vol1
        persistentVolumeClaim:
          claimName: demo-vol1-claim
      - name: basic-configmap
        configMap:
          name: basic
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-vol1-claim
spec:
  storageClassName: openebs-jiva-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5G"
