---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-jiva-limits
  annotations:
    cas.openebs.io/create-volume-template: jiva-volume-create-default-0.7.0
    cas.openebs.io/delete-volume-template: jiva-volume-delete-default-0.7.0
    cas.openebs.io/read-volume-template: jiva-volume-read-default-0.7.0
    cas.openebs.io/config: |
      - name: ControllerImage
        value: openebs/jiva:ci
      - name: ReplicaImage
        value: openebs/jiva:ci
      - name: VolumeMonitorImage
        value: openebs/m-exporter:ci
      - name: ReplicaCount
        value: "1"
      - name: StoragePool
        value: default
      - name: TargetResourceLimits
        value: |-
            memory: 1Gi
            cpu: 100m
      - name: AuxResourceLimits
        value: |-
            memory: 0.5Gi
            cpu: 50m
      - name: ReplicaResourceLimits
        value: |-
            memory: 2Gi
            cpu: 200m
provisioner: openebs.io/provisioner-iscsi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-jiva-limits-claim
spec:
  storageClassName: openebs-jiva-limits
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4G

