---

- name: Delete percona deployment
  include_tasks: "{{utils_path}}/delete_deploy.yml"
  vars:
    app_yml: "{{ percona }}"
    ns: "{{namespace}}"

- name: Confirm percona pod has been deleted
  include_tasks: "{{utils_path}}/delete_deploy_check.yml"
  vars:
    ns: "{{namespace}}"
    lkey: name
    lvalue: percona

- name: uncordon the node which is drained
  shell: source ~/.profile; kubectl uncordon {{ node1.stdout }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: "'uncordoned' in result.stdout"
  delay: 5
  retries: 10
  changed_when: True

- name: Delete storage class 
  shell: source ~/.profile; kubectl delete -f "{{ result_kube_home.stdout }}/{{ create_sc }}"
  args:
    executable: /bin/bash
  register: sc_out
  until: "'deleted' in sc_out.stdout"
  delay: 10
  retries: 5
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

- name: Remove test artifacts
  file:
    path: "{{ result_kube_home.stdout }}/{{ item }}"
    state: absent
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  with_items:
     - "{{test_artifacts}}"
     - "{{ percona }}"
     - "{{ create_sc }}"

