---

- name: Delete percona deployment
  include_tasks: "{{utils_path}}/delete_deploy.yml"
  vars:
    app_yml: "{{ percona_file }}"
    ns: "{{namespace}}"

- name: Confirm percona pod has been deleted
  include_tasks: "{{utils_path}}/delete_deploy_check.yml"
  vars:
    ns: "{{namespace}}"
    lkey: name
    lvalue: percona

- name: uncordon the node which is drained
  shell: source ~/.profile; kubectl uncordon {{ node1.stdout }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: "'uncordoned' in result.stdout"
  delay: 5
  retries: 10
  changed_when: True

- name: Delete storage class 
  shell: source ~/.profile; kubectl delete -f "{{ create_sc }}"
  args:
    executable: /bin/bash
  register: sc_out
  until: "'deleted' in sc_out.stdout"
  delay: 10
  retries: 5
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

- name: Replace the replica count in openebs-storageclasses yaml
  replace:
    path: "{{ result_kube_home.stdout }}/{{ create_sc }}"
    regexp: '      - name: ReplicaCount\n        value: "{{ (node_count) |int-1 }}"'
    replace: '      - name: ReplicaCount\n        value: "3"'
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

- name:  Apply storage class yaml
  shell: source ~/.profile; kubectl apply -f "{{ result_kube_home.stdout }}/{{ create_sc }}"
  args:
    executable: /bin/bash
  register: sc_out
  until: "'created' in sc_out.stdout"
  delay: 10
  retries: 5
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

- name: Remove test artifacts
  file:
    path: "{{ result_kube_home.stdout }}/{{ item }}"
    state: absent
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  with_items:
     - "{{test_artifacts}}"

