---
- name: apt-get update packages      
  apt:
    update_cache: yes
  become: true

- name: Install APT Packages
  apt: 
    name: "{{ item }}" 
    state: present
  with_items: "{{ deb_packages }}"
  become: true

- name: Create Directory
  file:
    path: "{{ansible_env.HOME}}/demo/openebs/"
    state: directory

- name: Download Maya
  get_url:
    url: "{{ item }}"
    dest:  "{{ansible_env.HOME}}/demo/openebs/"
    force: yes
  register: result
  until:  "'OK' in result.msg"
  delay: 5
  retries: 3
  with_items: "{{ openebs_maya_url }}"

- name: Unzip Maya
  unarchive:
    src: "{{ansible_env.HOME}}/demo/openebs/maya-linux_amd64.zip"
    dest: /usr/bin/
    remote_src: True
  become: true
