---
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-pool-default-0.7.0
  annotations:
    cas.openebs.io/create-pool-template: cstor-pool-create-default-0.7.0
    cas.openebs.io/delete-pool-template: cstor-pool-delete-default-0.7.0
spec:
  name: cstor-pool-default-0.7.0
  type: openebs-cstor
  maxPools: 3
  poolSpec:
    poolType: striped
    cacheFile: /tmp/pool1.cache
    overProvisioning: false
  # NOTE - Appropriate disks need to be fetched using `kubectl get disks`
  #
  # `Disk` is a custom resource supported by OpenEBS with `node-disk-manager` 
  # as the disk operator
  disks:
    diskList:
# Replace the following with actual disk CRs from your cluster `kubectl get disks`
#      - disk-0c84c169ab2f398b92914f56dad41f81
#      - disk-66a74896b61c60dcdaf7c7a76fde0ebb
#      - disk-b34b3f97840872da9aa0bac1edc9578a
