---
- name: Get pv name to verify successful pvc deletion
  shell: source ~/.profile; kubectl get pvc | grep {{ volume_claim }} | awk {'print $3'}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: pv
  changed_when: true

- name: Delete jupyter server pod
  include_tasks: "{{utils_path}}/delete_deploy.yml"
  vars:
    ns: default
    app_yml: "{{ pod_yaml_alias }}"

- name: Confirm jupyter pod has been deleted
  include_tasks: "{{utils_path}}/delete_deploy_check.yml"
  vars:
    ns: default
    lkey: name
    lvalue: jupyter-server

- name: Confirm pvc pod has been deleted
  shell: source ~/.profile; kubectl get pods
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: "pv.stdout not in result.stdout"
  delay: 30
  retries: 10
  changed_when: true

- name: Remove the copied test specific artifacts
  file:
    path: "{{result_kube_home.stdout}}/{{item}}"
    state: absent
  with_items:
    - "{{ pod_yaml_alias }}"
