---
- name: Wait {{ io_run_duration }} sec for I/O completion
  wait_for:
    timeout: "{{ io_run_duration }}"

- name: Unmount the ext4 filesystem
  mount: 
    name: /mnt/iscsi
    state: absent 
  become: true

- name: Tear down iSCSI sessions
  open_iscsi: 
    login: no
    portal: "{{hostvars[groups['openebs-mayamasters'][0]]['openebs_target_portal']}}"
    target: "{{hostvars[groups['openebs-mayamasters'][0]]['openebs_target_iqn']}}"
  become: true

- name: Remove stale node entries for ISCSI target
  shell: iscsiadm -m node -T "{{hostvars[groups['openebs-mayamasters'][0]]['openebs_target_iqn']}}" -o delete
  become: true

- name: Tear down the storage containers
  shell: source ~/.profile; maya vsm-stop {{openebs_vol_name}}
  args: 
    executable: /bin/bash
  ignore_errors: false 
  delegate_to: "{{groups['openebs-mayamasters'].0}}"
