---
- name: Get Master Status
  command: ansible "{{groups['openebs-mayamasters'].0}}" -m ping
  register: result_status
  delegate_to: 127.0.0.1

- name:
  debug:
    msg: "Ending play, Master UNREACHABLE."
  when: "'FAILED' in result_status.stdout"

- name: Ending Playbook Run - Master is not UP.
  meta: end_play
  when: "'FAILED' in result_status.stdout"

- name: Setup Maya      
  command: maya setup-osh -self-ip={{hostvars[inventory_hostname]['ansible_ssh_host']}} -omm-ips={{hostvars[groups['openebs-mayamasters'][0]]['ansible_ssh_host']}}
  become: true
