apiVersion: v2
version: 4.0.1
name: openebs
appVersion: 4.0.1
description: Containerized Attached Storage for Kubernetes
icon: https://raw.githubusercontent.com/cncf/artwork/HEAD/projects/openebs/icon/color/openebs-icon-color.png
home: https://www.openebs.io/
keywords:
  - cloud-native-storage
  - block-storage
  - local-storage
  - NVMe
  - storage
  - kubernetes
sources:
  - https://github.com/openebs/openebs
dependencies:
  - name: openebs-crds
    version: 4.0.0
  - name: localpv-provisioner
    version: 4.0.0
    repository: "https://openebs.github.io/dynamic-localpv-provisioner"
  - name: zfs-localpv
    version: 2.5.1
    repository: "https://openebs.github.io/zfs-localpv"
    condition: engines.local.zfs.enabled
  - name: lvm-localpv
    version: 1.5.1
    repository: "https://openebs.github.io/lvm-localpv"
    condition: engines.local.lvm.enabled
  - name: mayastor
    version: 2.6.1
    repository: "https://openebs.github.io/mayastor-extensions"
    condition: engines.replicated.mayastor.enabled
