release:
  version: "4.0.0"

# Refer to localpv-provisioner chart values.yaml for more configuration.
localpv-provisioner:
  rbac:
    create: true

# Refer to zfs-localpv chart values.yaml for more configuration.
zfs-localpv:
  enabled: true
  crds:
    zfsLocalPv:
      # -- For upgrades from previous zfs localpv installation this needs to be disabled.
      enabled: true
    csi:
      volumeSnapshots:
        # -- Default installation of the openebs unified chart will install crds from zfs depenendency chart.
        enabled: true
        # -- Disable this to uninstall crds on chart uninstallation.
        keep: true 
  
# Refer to lvm-localpv chart values.yaml for more configuration.
lvm-localpv:
  enabled: true
  crds:
    lvmLocalPv:
      # -- For upgrades from previous lvm localpv installation this needs to be disabled.
      enabled: true
    csi:
      volumeSnapshots:
        # -- Enable this if zfs chart installation is disabled.
        enabled: false
        # -- Disable this to uninstall crds on chart uninstallation.
        keep: true

# Refer to mayastor chart values.yaml for more configuration.
mayastor:
  enabled: true
  csi:
    node:
      initContainers:
        enabled: true

  localpv-provisioner:
    enabled: false
  crds:
    jaeger:
      # -- For upgrades from 2.5 mayastor chart this needs to be disabled.
      enabled: true
      # -- Disable this to uninstall crds on chart uninstallation.
      keep: true
    csi:
      volumeSnapshots:
        # -- Enable this if zfs chart installation is disabled. For upgrades from previous mayastor installation this needs to be disabled.
        enabled: false
        # --Disable this to uninstall crds on chart uninstallation.
        keep: true

# -- Configuration options for pre-upgrade helm hook job.
preUpgradeHook:
  image:
    # -- The container image registry URL for the hook job
    registry: docker.io
    # -- The container repository for the hook job
    repo: bitnami/kubectl
    # -- The container image tag for the hook job
    tag: "1.25.15"
    # -- The imagePullPolicy for the container
    pullPolicy: IfNotPresent

engines:
  local:
    lvmEnabled: true
    zfsEnabled: true
  replicated:
    mayastorEnabled: true
