---
- name: Delete cassandra service pod
  shell: source {{ profile }}; kubectl delete -f {{ svc_yaml_alias }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  changed_when: true

- name: Delete cassandra statefulset pod
  shell: source {{ profile }}; kubectl delete -f {{ stateful_yaml_alias }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  changed_when: true

- name: Delete cassandra loadgen pod
  shell: source {{ profile }}; kubectl delete -f {{ loadgen_yaml_alias }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  changed_when: true

- name: Get pvcs
  shell: source {{ profile }}; kubectl get pvc -o custom-columns=:metadata.name --no-headers | grep cassandra-data
  args:
    executable: /bin/bash
  register: result
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  changed_when: true

- name: Delete pvcs
  shell: source {{ profile }}; kubectl delete pvc {{ item }}
  args:
    executable: /bin/bash
  with_items:
    - "{{ result.stdout_lines }}"
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  changed_when: true

- name: Confirm cassandra pod has been deleted
  shell: source {{ profile }}; kubectl get pods
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: "'cassandra' not in result.stdout"
  delay: 120
  retries: 6
  changed_when: true
