---
- name: Delete cassandra service pod
  include_tasks: "{{utils_path}}/delete_deploy.yml"
  vars:
    ns: "{{ namespace }}"
    app_yml: "{{ svc_yaml_alias }}"

- name: Delete cassandra statefulset pod
  include_tasks: "{{utils_path}}/delete_deploy.yml"
  vars:
    ns: "{{ namespace }}"
    app_yml: "{{ stateful_yaml_alias }}"

- name: Get cassandra pvcs
  shell: source ~/.profile; kubectl get pvc -n {{ namespace }} -o custom-columns=:metadata.name --no-headers | grep cassandra-data
  args:
    executable: /bin/bash
  register: result
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  changed_when: true

- name: Delete cassandra pvcs
  shell: source {{ profile }}; kubectl delete pvc -n {{ namespace }} {{ item }}
  args:
    executable: /bin/bash
  with_items:
    - "{{ result.stdout_lines }}"
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  changed_when: true

- name: Confirm cassandra pod has been deleted
  shell: source {{ profile }}; kubectl get pods
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: "'cassandra' not in result.stdout"
  delay: 120
  retries: 6
  changed_when: true

- name: Get cassandra deploy
  shell: source {{ profile }}; kubectl get deploy -n {{ namespace }} --no-headers | awk {'print $1'}
  args:
    executable: /bin/bash
  register: result
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  changed_when: true

- name: Delete cassandra deploy
  shell: source {{ profile }}; kubectl delete deploy {{ item }} -n {{ namespace }}
  args:
    executable: /bin/bash
  with_items:
    - "{{ result.stdout_lines }}"
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  changed_when: true
  ignore_errors: true

- name: Delete cassandra loadgen pod
  include_tasks: "{{utils_path}}/delete_deploy.yml"
  vars:
    ns: "{{ namespace }}"
    app_yml: "{{ loadgen_yaml_alias }}"

- name: Delete namespace
  shell: source ~/.profile; kubectl delete ns {{ namespace }}
  args:
    executable: /bin/bash
  delegate_to: "{{ groups['kubernetes-kubemasters'].0 }}"
  register: result
  until: "'deleted' in result.stdout"
  delay: 10
  retries: 5
  changed_when: True

- name: Remove test artifacts
  file:
    path: "{{ result_kube_home.stdout }}/{{ item }}"
    state: absent
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  with_items:
    - "{{ svc_yaml_alias }}"
    - "{{ stateful_yaml_alias }}"
    - "{{ loadgen_yaml_alias }}"
