# Default values for openebs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  create: true
  name:

image:
  pullPolicy: IfNotPresent

apiserver:
  image: "openebs/m-apiserver"
  imageTag: "0.5.4"
  replicas: 1
  ports:
    externalPort: 5656
    internalPort: 5656
  nodeSelector: {}
  tolerations: {}
  affinity: {}

provisioner:
  image: "openebs/openebs-k8s-provisioner"
  imageTag: "0.5.4"
  replicas: 1
  nodeSelector: {}
  tolerations: {}
  affinity: {}

jiva:
  image: "openebs/jiva"
  imageTag: "0.5.4"
  replicas: 3

grafana:
  image: "grafana/grafana"
  imageTag: "4.6.3"
  ports:
    externalPort: 3000
    internalPort: 3000
    nodePort: 32515

prometheus:
  image: "prom/prometheus"
  imageTag: "v2.1.0"
  ports:
    externalPort: 80
    internalPort: 9090
    nodePort: 32514

policies:
  monitoring:
    enabled: true
    image: "openebs/m-exporter"
    imageTag: "0.5.4"
