---
- name: Deletion of test specific  namespace.
  shell: source ~/.profile; kubectl delete ns {{ namespace }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

- name: Check the namespace status.
  shell: source ~/.profile; kubectl get ns 
  args:
    executable: /bin/bash
  register: np
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  until: "'{{ namespace }}' not in np.stdout"
  delay: 30
  retries: 15
  ignore_erros: true
