---
- name: Deploy application files
  shell: source ~/.profile; kubectl apply -f "{{result_kube_home.stdout}}/{{ item }}" -n {{ ns }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  with_items: "{{ app_yml }}"


