---
- name: Update Testrail
  shell: source ~/.profile; python3 {{ inventory_dir | dirname }}/files/updater.py -tuser {{ testrail_user }} -tpass {{ testrail_password }} -sid {{ suite_id }} -cid {{ case_id }} -stid {{ st_id }} -et {{ storage_engine }}
  args:
    executable: /bin/bash
  register: result
  ignore_errors: yes

- name: Testrail Updated
  set_fact:
    tflag: "{{ result.stdout }}"

- name: Send slack notification
  slack:
    token: "{{ lookup('env','SLACK_TOKEN') }}"
    msg: '{{ ansible_date_time.time }} TEST: {{t_name}}, RESULT: {{ t_status }},{{ c_status }},{{tflag}}'
    color: "{{color}}"
  when: slack_notify | bool and lookup('env','SLACK_TOKEN')
  ignore_errors: yes
