---
- name: Create Directory
  file:
    path: "{{ weave_images_path }}"
    state: directory

- name: Copy TAR to remote
  copy:
    src: "{{ weave_depends[0] }}"
    dest: "{{ weave_images_path }}"
  become: true

- name: Copy Pod YAML to remote
  copy:
    src: "{{ weave_depends[1] }}"
    dest: "{{ weave_images_path }}"

- name: Copy Script to remote
  copy:
    src: "{{ configure_scripts[1] }}"
    dest: "{{ k8s_images_path }}"
    mode: "u+rwx"

- name: Load images from Archive
  command: docker load --input "{{ k8s_images }}"
  args:
    chdir: "{{ k8s_images_path }}"
  become: true

- name: Load images from Archive
  command: docker load --input "{{ weave_depends[0] }}"
  args:
    chdir: "{{ weave_images_path }}"
  become: true

- name: Install deb packages
  apt:
    deb: "{{ k8s_images_path }}/{{ item }}"
  with_items: "{{ k8s_dpkg_packages }}"
  become: true

- name: kubeadm reset before init
  command: kubeadm reset
  become: true

- name: kubeadm init
  script: "{{ configure_scripts[0] }}"
  become: true

- name: Get Current User
  command: whoami
  register: user

- name: Copy k8s credentials to $HOME 
  copy:
    src: "/etc/kubernetes/admin.conf" 
    remote_src: True
    dest: "{{ ansible_env.HOME}}"
  become: true

- name: Change file permissions
  file:
    path: "{{ ansible_env.HOME }}"
    owner: "{{ user.stdout }}"
    group: "{{ user.stdout }}"     
    state: directory
  become: true

- name: Update KUBECONFIG in .profile
  lineinfile:
    destfile : "{{ansible_env.HOME}}/.profile"
    line: export KUBECONFIG=$HOME/admin.conf
    state: present

- name: Patch kube-proxy for CNI Networks
  shell: source ~/.profile; "{{ k8s_images_path }}/{{ configure_scripts[1] }}" 
  args:
    executable: /bin/bash
