---
##################################################### PREPARATION OF K8S-LOCALHOST BOX #########################################################

deb_local_packages:
  - docker.io

pip_local_packages:
  - 'docker-py==1.9.0'

###################################################### PREPARATION OF KUBERNETES ROLE  ##########################################################

# Links for .deb packages that will be installed on all K8s boxes (masters, minions), i.e, 
# these packages will be copied into kubernetes role's .files

k8s_deb_packages:
  - https://packages.cloud.google.com/apt/pool/kubeadm_1.6.3-00_amd64_ff5e882c88a5db71803aab900c0b341eb63038558da73c51c3d351070b0c62af.deb
  - https://packages.cloud.google.com/apt/pool/kubectl_1.6.3-00_amd64_05d48fa118b6538ee2bc0b864aeb09f2cede83990fc8819875f698a5dece0c9b.deb
  - https://packages.cloud.google.com/apt/pool/kubelet_1.6.3-00_amd64_a94b0cfa5b26939d87097dfd45260474c1effcad879e35940eb6d36e7d953d6c.deb
  - https://packages.cloud.google.com/apt/pool/kubernetes-cni_0.5.1-00_amd64_08cbe5c42366ec3184cc91a4353f6e066f2d7325b4db1cb4f87c7dcc8c0eb620.deb

k8s_deb_package_alias:
  - kubeadm.deb
  - kubectl.deb
  - kubelet.deb
  - kubernetes-cni.deb

# Container images that needs to be placed on all K8s boxes (masters, minions)
# These images will be downloaded, tar'ed and pushed into the kubernetes role's .files

k8s_images:
  - gcr.io/google_containers/pause-amd64:3.0
  - gcr.io/google_containers/etcd-amd64:3.0.17
  - gcr.io/google_containers/kube-scheduler-amd64:v1.6.2
  - gcr.io/google_containers/kube-apiserver-amd64:v1.6.2
  - gcr.io/google_containers/kube-controller-manager-amd64:v1.6.2
  - gcr.io/google_containers/kube-proxy-amd64:v1.6.2
  - gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.1
  - gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.1
  - gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.1

###################################################### PREPARATION OF K8S-MASTER ROLE ###########################################################

# Links for scripts to be placed into K8s-master role's .files 

k8s_master_scripts: 
  - https://raw.githubusercontent.com/openebs/openebs/master/k8s/lib/scripts/configure_k8s_master.sh
  - https://raw.githubusercontent.com/openebs/openebs/master/k8s/lib/scripts/configure_k8s_weave.sh

# Container images that needs to be placed in K8s-master box
# These images will be downloaded, tar'ed and pushed into K8s-master role's .files 

weave_images: 
  - weaveworks/weave-kube:1.9.4
  - weaveworks/weave-npc:1.9.4

# Link to download default weave template (.yaml) to be placed in roles/kubernetes/templates

weave_template_link: https://raw.githubusercontent.com/openebs/openebs/master/k8s/lib/vagrant/boxes/k8s-weave/external/weave-daemonset-k8s-1.6.yaml

###################################################### PREPARATION OF K8S-HOST ROLE #############################################################

# Links for scripts to be placed into K8s-host role's .files

k8s_host_scripts: 
  - https://raw.githubusercontent.com/openebs/openebs/master/k8s/lib/scripts/configure_k8s_host.sh


