apiVersion: v1
kind: ConfigMap
metadata:
  name: upgrade-config
  namespace: default
data:
  upgrade: |
    casTemplate: jiva-volume-update-0.8.2-0.9.0
    resources:
    - name: pvc-58654bd9-7861-11e9-b212-54e1ad4a9dd4
      kind: jiva-volume
      namespace: default
---
apiVersion: batch/v1
kind: Job
metadata:
  name: volume-upgrade
spec:
  template:
    spec:
      serviceAccountName: super-admin
      containers:
      - name:  upgrade
        image: mittachaitu/m-upgrade:ci
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        env:
        - name: OPENEBS_IO_POD_NAME
#          value: spc-cstor-sparse-pool-upgrade
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPENEBS_IO_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPENEBS_IO_POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
      volumes:
      - name: config
        configMap:
          name: upgrade-config
      restartPolicy: Never
