---
- name: Delete percona mysql pod
  include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/delete_deploy.yml"
  vars:
    app_yml: "{{ pod_yaml_alias }}"
    ns: "{{ namespace }}"

- name: Confirm percona pod has been deleted
  include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/delete_deploy_check.yml"
  vars:
    app: "{{ pod_yaml_alias }}"
    ns: "{{  namespace }}"

- name: Make the current ctrl node schedulable
  shell: source ~/.profile; kubectl uncordon {{ctrl_node}}
  args:
    executable: /bin/bash
  register: result
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

