---
test_log_path: setup/logs/volume_taints.log

test_pod_regex: maya*|openebs*|pvc*

volume_policy: openebs-volumepolicies.yaml

storage_pool: storage-pool-path_creation.yml

test_name: Testing Volume taint policy

test-pvc: https://raw.githubusercontent.com/openebs/openebs/master/e2e/ansible/playbooks/hyperconverged/test-k8s-storage-pool/test-pvc.yaml 

operator_key: key1

operator_value: value1

pvc_key: key2

pvc_value: value2

namespace: cas-template 

node1: kubeminion-01

operator_list:
       - 'key: "k"'
       - 'value: "v"'
replaceoperator_list: 
              - 'key: "key1"'
              - 'value: "value1"'
list:
   - "key: jk"
   - "value: jv"

replace_list:
   - "key: key2"
   - "value: vaule2"

node_names:
  - kubeminion-02
  - kubeminion-03

test_artifacts:
  -  storage-pool-path_creation.yml
  -  openebs-volumepolicies.yaml
  -  test-pvc.yaml
