{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "openebs.fullname" . }}
  labels:
    app: {{ template "openebs.name" . }}
    chart: {{ template "openebs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
# Allow OpenEBS read-only access to a few cluster-wide objects.
- apiGroups: ["*"]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["nodes/proxy"]
  verbs: ["get"]
- apiGroups: ["*"]
  resources: ["namespaces"]
  verbs: ["get", "watch"]
# Allow OpenEBS to manage persistent storage cluster-wide.
- apiGroups: ["*"]
  resources:
  - storageclasses
  - persistentvolumeclaims
  - persistentvolumes
  verbs: ["*"]
# Allow OpenEBS to create events.
- apiGroups: ["*"]
  resources:
  - events
  verbs: ["create"]
# Allow OpenEBS to register its custom objects.
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]
# Allow OpenEBS to manage its own custom objects cluster-wide.
- apiGroups: ["*"]
  resources:
  - disks
  - blockdevices
  - blockdeviceclaims
  - cstorpoolclusters
  - storagepoolclaims
  - storagepoolclaims/finalizers
  - cstorpoolclusters/finalizers
  - storagepools
  - castemplates
  - runtasks
  - upgradetasks
  - cstorpools
  - cstorpools/finalizers
  - cstorvolumereplicas
  - cstorvolumes
  - cstorvolumeclaims
  - cstorpoolinstances
  - cstorpoolinstances/finalizers
  - cstorbackups
  - cstorrestores
  - cstorcompletedbackups
  verbs: ["*"]
- apiGroups: ["volumesnapshot.external-storage.k8s.io"]
  resources:
  - volumesnapshots
  - volumesnapshotdatas
  verbs: ["*"]
# Allow OpenEBS to install and manage its own admission webhooks.
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  verbs: ["list", "create"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  resourceNames: ["openebs-validation-webhook-cfg"]
  verbs: ["*"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
{{- end }}
