---

- name: Get Current User
  command: whoami
  register: user
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

- name: Get $HOME of K8s master for kubernetes user
  shell: source ~/.profile; echo $HOME
  args:
    executable: /bin/bash
  register: result_kube_home
  changed_when: true

- name: Get Log Aggregator
  get_url:
    url: "{{k8s_log_aggregator_url}}"
    dest: "{{result_kube_home.stdout}}"
    force: yes
  register: result
  until: "'OK' in result.msg"
  delay: 5
  retries: 3

- name: Copy log aggregator to remote
  copy:
    src: "{{ k8s_log_aggregator }}"
    owner: "{{ user.stdout }}"
    group: "{{ user.stdout }}"
    dest: /usr/local/bin
    mode: "u+rwx"
  become: true

- stat:
    path: "{{ k8s_logs_path }}"
  register: status

- name: Create Directory
  file:
    path: "{{ k8s_logs_path }}"
    state: directory
  become: true
  when: status.stat.isdir is not defined

- stat:
    path: "{{ k8s_logs_path }}"
  register: status

- name: Change Folder Permissions
  file:
    path: "{{ k8s_logs_path }}"
    owner: "{{ user.stdout }}"
    group: "{{ user.stdout }}"
    recurse: true
  become: true
  when: status.stat.isdir is defined and status.stat.isdir
