---
test_name: test-disk-failure

create_sc: storage-class.yaml

storage_pool_link: https://raw.githubusercontent.com/openebs/openebs/master/e2e/ansible/playbooks/hyperconverged/test-k8s-storage-pool/storage-pool-path_creation.yml

sql_test_link: https://raw.githubusercontent.com/openebs/elves/master/e2e/percona-liveness/sql-test.sh

percona_link: https://raw.githubusercontent.com/openebs/elves/master/e2e/percona-liveness/percona.yaml

percona_files:
  - percona.yaml
  - sql-test.sh
  - storage-pool-path_creation.yml

replace_item:
  - default
  - /mnt/openebs

replace_with:
  - disk
  - "{{result_mountpoint.stdout}}"

test_pod_regex: maya*|openebs*|pvc*|percona*
 
test_log_path: setup/logs/test-disk-failure.log

namespace: disk-failure
