---
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-sparse-pool
  annotations:
    cas.openebs.io/create-pool-template: cstor-pool-create-default-0.7.0
    cas.openebs.io/delete-pool-template: cstor-pool-delete-default-0.7.0
    cas.openebs.io/config: |
      - name: PoolResourceLimits
        value: |-
            memory: 2Gi
            cpu: 200m
      - name: AuxResourceLimits
        value: |-
            memory: 0.5Gi 
            cpu: 50m
spec:
  name: cstor-sparse-pool
  type: sparse
  maxPools: 3
  poolSpec:
    poolType: striped
    cacheFile: /tmp/cstor-sparse-pool.cache
    overProvisioning: false
