---
apiVersion: v1
kind: Pod
metadata:
  name: fio-jiva
  labels:
    name: fio-jiva
spec:
  containers:
  - resources:
      limits:
        cpu: 0.5
    name: fio-jiva
    image: openebs/tests-fio
    command: ["/fio_runner.sh"]
    args: ["Basic", "60"]
    tty: true
    volumeMounts:
    - mountPath: /datadir
      name: datavol
  volumes:
    - name: datavol
      persistentVolumeClaim:
        claimName: fio-jiva-claim 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-jiva-claim
spec:
  storageClassName: openebs-standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "4G"
 
