---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-jiva-limits
  annotations:
    openebs.io/cas-type: jiva
    cas.openebs.io/config: |
      - name: TargetResourceRequests
        value: |-
            memory: 0.5Gi
            cpu: 100m
      - name: TargetResourceLimits
        value: |-
            memory: 1Gi
      - name: ReplicaResourceRequests
        value: |-
            memory: 0.5Gi
            cpu: 100m
      - name: ReplicaResourceLimits
        value: |-
            memory: 2Gi
            cpu: 200m
      - name: AuxResourceLimits
        value: |-
            memory: 0.5Gi
            cpu: 50m
provisioner: openebs.io/provisioner-iscsi
---
apiVersion: v1
kind: Pod
metadata:
  name: fio-jiva
  labels:
    name: fio-jiva
spec:
  containers:
  - resources:
      limits:
        cpu: 0.5
    name: fio-jiva
    image: openebs/tests-fio
    command: ["/bin/bash"]
    args: ["-c", "./fio_runner.sh --template file/basic-rw --size 256m --duration 6000; exit 0"]
    tty: true
    volumeMounts:
    - mountPath: /datadir
      name: datavol
  volumes:
    - name: datavol
      persistentVolumeClaim:
        claimName: fio-jiva-claim 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-jiva-claim
spec:
  storageClassName: openebs-jiva-limits
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "4G"
 
