# GitHub Action to automate the identification of common misspellings in text files
# https://github.com/codespell-project/codespell
name: codespell
on: [push, pull_request]
jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install codespell flake8
      - run: codespell --ignore-words="./.codespell-ignores.txt" --skip="./.git,*.png,*.jpg,*.ico,*.pdf,get-pip.py,dynamo"
      - name: Codespell comment
        if: ${{ failure() }}
        uses: plettich/python_codespell_action@master
